### ISSUE TITLE
AsncTCPSocket destroyed (Firewall issue?)

### ISSUE THREAD

**Issue by MagmaiKH** [rglx/SEDS-Setup#11]
I get the server running and am trying to direct connect to the server but I get this sequences of errors.
I'm having trouble tracking down what ports SEDS uses.
I found UDP 27016 but the log below clearly says TCP.
I tried disabling the firewall but I still get this error.

2015-09-25 01:57:18.330: Game ready... Press Ctrl+C to exit
2015-09-25 01:57:34.717: Peer2Peer_SessionRequest 76561198000602144
STEAMPS3 - AsyncTCPSocket created
STEAMPS3 - AsncTCPSocket destroyed
2015-09-25 01:57:49.720: User left

**Comment by Revii** [comment]
Same here:

2015-09-25 04:29:58.695: Peer2Peer_SessionRequest 76561198020746232
STEAMPS3 - AsyncTCPSocket created
STEAMPS3 - AsncTCPSocket destroyed
2015-09-25 04:30:13.715: User left

After fresh installation. :/

**Comment by ADWshka** [comment]
Came across with such a problem that occurs on OpenVZ virtual servers. Everything works fine on real hardware. After searching the Web came to the conclusion that it is not just a problem of SE.

**Comment by MagmaiKH** [comment]
It's possible it's due to the older kernel; 2.6.32-042stab102.9

**Comment by ArghArgh200** [comment]
Stop suggesting things that don't make sense!

This is the PS3/4 part of the Steam API that just breaks. Ignore it.
Happens on Windows servers too.

**Comment by ArghArgh200** [comment]
As for the original issue, you do need to open a second port in your firewall, by default I think it's 8700 or something. Start the server GUI on your windows machine and look for the 'Steam port'. I've gotten this server to run on Debian 6 boxes virtualized by OpenVZ with kernel version 2.6, so that's not the problem.

**Comment by MagmaiKH** [comment]
The error is that users fail to download the world data after they connect.
(The TCP socket disconnection is not an error. That's just the log of what is happening.)
The first thing I tried was disabling the firewall and it behaved the same way.

Myself (and others) have had problems running it under OpenVZ; it could be something in the OpenVZ config or some options in the kernel. It's the same version of wine in the working and not-working cases so that eliminates a lot of variability on the user-side.
