### ISSUE TITLE
Working with planets?

### ISSUE THREAD

**Issue by Frozen-byte** [rglx/SEDS-Setup#16]
Space Engineers requires DirectX11 for planets.
Does this affect the Dedicated-Server as well?
Am I able to go with wine 1.7.30+ and planets?

**Comment by phit** [comment]
server in wine is currently broken, but because a different issue [more information](http://forum.keenswh.com/threads/new-dedicated-server-ubuntu-14-se.7372972/#post-1286882205)

**Comment by Frozen-byte** [comment]
I don't think the Forum is right and everything will be fine with 64bit.
Since it fails to load the planets map (and asteroids works fine) I guess it is likely the DX11 dependency.

**Comment by phit** [comment]
directx11 is not a requirement for the server, that would be horrible for server providers if they would need a graphics card ;)
i just tested myself, the 32bit version runs out of memory when creating a world with the EarthEasyStart preset, even on my personal windows machine
BUT when you create the world with 64bit under windows and copy that to the linux machine the server starts up just fine
![proof](https://cloud.githubusercontent.com/assets/2097483/11165235/0309930c-8b0a-11e5-9a01-10c0812f8718.png)

but as you can see, you still run into memory issues :/ 
and unless [dotnet40](https://appdb.winehq.org/objectManager.php?sClass=version&iId=17886) will start supporting 64bit, we won't be able to run the 64bit server ever

**Comment by Frozen-byte** [comment]
Hm, so we need to wait for a x64 .NET version, if it ever comes.

btw, nice Solarized theme tho ;)
