### ISSUE TITLE
Wine is unable to find SpaceEngineersDedicated.exe file and weird error with worldcleaner.py file

### ISSUE THREAD

**Issue by Atomicbeast101** [rglx/SEDS-Setup#22]
I am not able to get the server running due to two errors I'm receiving:
`wine: cannot find L"C:\\windows\\system32\\SpaceEngineersDedicated.exe"`
`../../worldcleaner.py: Permission denied
Traceback (most recent call last):
  File "../../worldcleaner.py", line 17, in <module>
    origfile = open('Sandbox.sbc').read()`

There is no worldcleaner.py file in spaceengineers folder so I do not know why it's throwing that error.

Here is my full error log:
`Redirecting stderr to '/home/ndroot/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...Created shared memory when not owner SteamController_Shared_mem
OK.

Connecting anonymously to Steam Public...Logged in OK
Waiting for license info...OK
Success! App '298740' already up to date.
./start.sh: line 19: cd: config/Saves/SEDSWorld: No such file or directory
Cleaning world of dead NPC entries - Credits to Andy_S of #space-engineers
../../worldcleaner.py: Permission denied
Traceback (most recent call last):
  File "../../worldcleaner.py", line 17, in <module>
    origfile = open('Sandbox.sbc').read()
IOError: [Errno 2] No such file or directory: 'Sandbox.sbc'
./start.sh: line 25: cd: /home/ndroot/.wine/drive_c/users/ndroot/Desktop/spaceengineers/DedicatedServer: No such file or directory
wine: cannot find L"C:\windows\system32\SpaceEngineersDedicated.exe"
./start.sh: line 30: cd: ../config: No such file or directory
mv: cannot stat ‘SpaceEngineersDedicated.log’: No such file or directory
cp: cannot stat ‘Saves/SEDSWorld’: No such file or directory`

**Comment by exit151** [comment]
My server has been running fine for several months perfectly fine using this script.
After the last Keen SE update, I too am getting this exact error.  I thought at first perhaps Ubuntu/wine updated on me, but after scouring history logs and whatnot, it seems the only thing that updated was SE, as usual on Thursday.  
I'm not wise enough to know what possibly could have changed, but something broke SE dedicated from running properly in wine somehow :(
I have even tried wiping my .wine folder (and configuration) as well as the spaceengineers folder, ensuring a fresh start in case something got corrupted with no luck.

**Comment by ArghArgh200** [comment]
Doesn't look like the folders and stuff are correct anymore.

TBH this is a dead project now that Keen's killed the 32-bit binaries, and until they stop doing nothing but half-patching bugs and half-implementing features I'm not going to do too much work on this. 64-bit support is out of the question until WINE gets .NET 4 support working under it, meaning we're waiting on either Keen for the Linux dedicated server, or the WINE dev team to get that working. My bet's on the WINE team, since they have a nice track record of finishing things they start.

**Comment by exit151** [comment]
Oh man, that really sucks.  I was not aware they did away with the 32bit version.. Why would they do that?!  So dumb.  Well - I'll check back from time to time, installing virtual machine on my box now, but that was never the way I wanted to go about it.  Thanks for an awesome script man, I used it for many months and loved being able to host my SE server on a linux box.  Shame they had to go and ruin it. :(

**Comment by mccorkle** [comment]
They did create a legacy / beta channel for 32bit/dx9. It might be possible to pull from that.  I'm told that there won't be any more updates to that branch though.

**Comment by Atomicbeast101** [comment]
It looks like wine is able to support .NET 4: [https://appdb.winehq.org/objectManager.php?sClass=version&iId=17886](url)

**Comment by DarthDestroyer** [comment]
yeah! of course! wine already supports .net 4.0 for a long time... 
and that isnt the Problem! The Problem is, that it only work in a 32bit Environment... what doesnt help us... :-(
