### ISSUE TITLE
Issues running on a non-Debian/Ubuntu OS? Read this!

### ISSUE THREAD

**Issue by rglx** [rglx/SEDS-Setup#3]
The script was designed to be run on a Debian- or Ubuntu-based OS with bash and a few other basic tools installed along with WINE. Any others are not supported, but if you can run wine, wget, winetricks, python, and bash on it, you can probably run the script. Post results here, and I'll edit this issue to reflect your experiences.

CONFIRMED WORKING WITH VERY LITTLE OR NO CHANGES:
- Ubuntu 13 **_AND UP**_ 64bit headless (With WINE PPA installer) + wine 1.7.44

CONFIRMED WORKING WITH SOME CHANGES: (Please provide details!)
- Debian 7 64bit headless (With self-compiled WINE and winetricks)
- Ubuntu 12.04 64bit headless (With WINE PPA installer) + wine 1.7.18 (Thanks ADWshka!)

CONFIRMED WORKING WITH LARGE CHANGES:
- None yet

CONFIRMED BROKEN
- None yet

**Comment by ADWshka** [comment]
WORKING WITH VERY LITTLE OR NO CHANGES:
+Ubuntu 14.04 64bit headless (With WINE PPA installer) + wine 1.7.44
+Ubuntu 15.04 64bit headless (With WINE PPA installer) + wine 1.7.44
WORKING WITH SOME CHANGES:
+Ubuntu 12.04 64bit headless (With WINE PPA installer) + wine 1.7.18

**Comment by ArghArgh200** [comment]
Mind noting what you did to get it working?

**Comment by ADWshka** [comment]
I had to remove part of the "start case", for some reason Python was not working, perhaps it is connected with the Python library on my OS.
