### ISSUE TITLE
Server crashing when SSH session ends

### ISSUE THREAD

**Issue by ajanvier** [rglx/SEDS-Setup#9]
Hello,

Thanks to your script I can finally run SEDS on Debian 7.
Everything runs perfectly, the screen is created and I can access it using

```
screen -x spaceengineers 
```

And detach it using Ctrl + A + D.

BUT, when I disconnect from my SSH session, the server crashed, apparently because of X11.

Do you have an idea on how to resolve that issue ?
Thanks a lot,

PS : By the way I have no idea where I can find a log about the exact error occuring, but I'll search.

**Comment by ArghArgh200** [comment]
Are you using X11 forwarding and/or did you remove the -console argument
from the script where it actually runs the server? Only things I can see
causing that. Maybe a WINE bug too. Dunno.

**Comment by ajanvier** [comment]
I don't know, I didn't edit anything in the script.
A Wine bug ? By the way I'm using Wine 1.7.47.

**Comment by MagmaiKH** [comment]
If you are having trouble with scren, nohup is an older/simpler way to avoid this issue.
i.e. When the session terminates (e.g. ssh connection ends) it sends the "hang-up" signal to all child processors which will cause them to close. nohup will eat the signal and ignore it (so will screen).

**Comment by ArghArgh200** [comment]
Actually you really don"t want to do that. Not with WINE, or a process that
runs for a long time and needs an interactive console like SE's dedicated
server (the Ctrl-C to exit is a [poorly written and supported] example of
this.)

**Comment by ArcanumSK** [comment]
Same issue here, other screens working ok, this will just quit on closing ssh connection (detached screen)
